// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZG4eb3f07cWwuBUZlWtDS8Du5gT_WCYo',
    appId: '1:20100769610:web:61398a426b5bfa514a83b3',
    messagingSenderId: '20100769610',
    projectId: 'teachmewell-esof',
    authDomain: 'teachmewell-esof.firebaseapp.com',
    databaseURL: 'https://teachmewell-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teachmewell-esof.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCockMIF8tf9Z7_wz3xC7fG8xQEgD8HqIo',
    appId: '1:20100769610:android:db0e09ac911f3aa64a83b3',
    messagingSenderId: '20100769610',
    projectId: 'teachmewell-esof',
    databaseURL: 'https://teachmewell-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teachmewell-esof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIud3h3peXHWL4sZHH3KzQHzrMHySZPK4',
    appId: '1:20100769610:ios:ae0349635595d9844a83b3',
    messagingSenderId: '20100769610',
    projectId: 'teachmewell-esof',
    databaseURL: 'https://teachmewell-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teachmewell-esof.appspot.com',
    iosClientId: '20100769610-q9mlrb0npv3tifsdgr6bvaq4fu7q3hhe.apps.googleusercontent.com',
    iosBundleId: 'com.esof.teachmewell.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIud3h3peXHWL4sZHH3KzQHzrMHySZPK4',
    appId: '1:20100769610:ios:ae0349635595d9844a83b3',
    messagingSenderId: '20100769610',
    projectId: 'teachmewell-esof',
    databaseURL: 'https://teachmewell-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teachmewell-esof.appspot.com',
    iosClientId: '20100769610-q9mlrb0npv3tifsdgr6bvaq4fu7q3hhe.apps.googleusercontent.com',
    iosBundleId: 'com.esof.teachmewell.app',
  );
}
