// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCockMIF8tf9Z7_wz3xC7fG8xQEgD8HqIo',
    appId: '1:20100769610:android:4fd437f64b982fa44a83b3',
    messagingSenderId: '20100769610',
    projectId: 'teachmewell-esof',
    databaseURL: 'https://teachmewell-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teachmewell-esof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIud3h3peXHWL4sZHH3KzQHzrMHySZPK4',
    appId: '1:20100769610:ios:2b9635973900878e4a83b3',
    messagingSenderId: '20100769610',
    projectId: 'teachmewell-esof',
    databaseURL: 'https://teachmewell-esof-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'teachmewell-esof.appspot.com',
    iosClientId: '20100769610-l6ipok81b6sq8cha6pk4g9gi6s5114fk.apps.googleusercontent.com',
    iosBundleId: 'com.esof.teachmewell.teachmewell',
  );
}
